CREATE TABLE public.restaurants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,

  address text,
  city text,
  postal_code text,
  country text,

  latitude numeric(9, 6),
  longitude numeric(9, 6),

  status text NOT NULL DEFAULT 'active',

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT restaurants_name_not_empty
    CHECK (length(trim(name)) > 0),

  CONSTRAINT restaurants_slug_not_empty
    CHECK (length(trim(slug)) > 0),

  CONSTRAINT restaurants_status_valid
    CHECK (status IN ('active', 'inactive')),

  CONSTRAINT restaurants_latitude_valid
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),

  CONSTRAINT restaurants_longitude_valid
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);