-- ============================================================
-- RestaurantOS
-- Migration: Menu Dietary Attributes & Allergens
-- ============================================================

-- ============================================================
-- 1. CATÁLOGO DE CARACTERÍSTICAS DIETÉTICAS
-- ============================================================

CREATE TABLE public.dietary_attributes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  code text NOT NULL UNIQUE,

  name text NOT NULL,

  description text,

  display_order integer NOT NULL DEFAULT 0,

  is_active boolean NOT NULL DEFAULT true,

  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT dietary_attributes_code_not_empty
    CHECK (length(trim(code)) > 0),

  CONSTRAINT dietary_attributes_name_not_empty
    CHECK (length(trim(name)) > 0),

  CONSTRAINT dietary_attributes_display_order_non_negative
    CHECK (display_order >= 0)
);


-- ============================================================
-- 2. CATÁLOGO DOS 14 ALERGÉNIOS
-- ============================================================

CREATE TABLE public.allergens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  code text NOT NULL UNIQUE,

  name text NOT NULL,

  description text,

  display_order integer NOT NULL DEFAULT 0,

  is_active boolean NOT NULL DEFAULT true,

  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT allergens_code_not_empty
    CHECK (length(trim(code)) > 0),

  CONSTRAINT allergens_name_not_empty
    CHECK (length(trim(name)) > 0),

  CONSTRAINT allergens_display_order_non_negative
    CHECK (display_order >= 0)
);


-- ============================================================
-- 3. RELAÇÃO MENU ITEM ↔ DIETARY ATTRIBUTES
-- ============================================================

CREATE TABLE public.menu_item_dietary_attributes (
  menu_item_id bigint NOT NULL,

  dietary_attribute_id bigint NOT NULL,

  created_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (
    menu_item_id,
    dietary_attribute_id
  ),

  CONSTRAINT menu_item_dietary_attributes_menu_item_fkey
    FOREIGN KEY (menu_item_id)
    REFERENCES public.menu_items(id)
    ON DELETE CASCADE,

  CONSTRAINT menu_item_dietary_attributes_attribute_fkey
    FOREIGN KEY (dietary_attribute_id)
    REFERENCES public.dietary_attributes(id)
    ON DELETE RESTRICT
);


-- ============================================================
-- 4. RELAÇÃO MENU ITEM ↔ ALERGÉNIOS
-- ============================================================

CREATE TABLE public.menu_item_allergens (
  menu_item_id bigint NOT NULL,

  allergen_id bigint NOT NULL,

  created_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (
    menu_item_id,
    allergen_id
  ),

  CONSTRAINT menu_item_allergens_menu_item_fkey
    FOREIGN KEY (menu_item_id)
    REFERENCES public.menu_items(id)
    ON DELETE CASCADE,

  CONSTRAINT menu_item_allergens_allergen_fkey
    FOREIGN KEY (allergen_id)
    REFERENCES public.allergens(id)
    ON DELETE RESTRICT
);


-- ============================================================
-- 5. ÍNDICES
-- ============================================================

CREATE INDEX menu_item_dietary_attributes_attribute_id_idx
  ON public.menu_item_dietary_attributes (
    dietary_attribute_id
  );

CREATE INDEX menu_item_allergens_allergen_id_idx
  ON public.menu_item_allergens (
    allergen_id
  );


-- ============================================================
-- 6. CARACTERÍSTICAS DIETÉTICAS INICIAIS
-- ============================================================

INSERT INTO public.dietary_attributes (
  code,
  name,
  description,
  display_order
)
VALUES
  (
    'vegetarian',
    'Vegetarian',
    'Suitable for a vegetarian diet.',
    1
  ),
  (
    'vegan',
    'Vegan',
    'Suitable for a vegan diet.',
    2
  ),
  (
    'gluten_free',
    'Gluten Free',
    'Suitable for a gluten-free diet.',
    3
  ),
  (
    'lactose_free',
    'Lactose Free',
    'Suitable for a lactose-free diet.',
    4
  ),
  (
    'spicy',
    'Spicy',
    'Contains spicy ingredients.',
    5
  );


-- ============================================================
-- 7. OS 14 ALERGÉNIOS DA UNIÃO EUROPEIA
-- ============================================================

INSERT INTO public.allergens (
  code,
  name,
  description,
  display_order
)
VALUES
  (
    'gluten_cereals',
    'Cereals containing gluten',
    'Cereals containing gluten, including wheat, rye, barley, oats and their products.',
    1
  ),
  (
    'crustaceans',
    'Crustaceans',
    'Contains crustaceans or products derived from crustaceans.',
    2
  ),
  (
    'eggs',
    'Eggs',
    'Contains eggs or products derived from eggs.',
    3
  ),
  (
    'fish',
    'Fish',
    'Contains fish or products derived from fish.',
    4
  ),
  (
    'peanuts',
    'Peanuts',
    'Contains peanuts or products derived from peanuts.',
    5
  ),
  (
    'soybeans',
    'Soybeans',
    'Contains soybeans or products derived from soybeans.',
    6
  ),
  (
    'milk',
    'Milk',
    'Contains milk or products derived from milk, including lactose.',
    7
  ),
  (
    'nuts',
    'Nuts',
    'Contains tree nuts or products derived from nuts.',
    8
  ),
  (
    'celery',
    'Celery',
    'Contains celery or products derived from celery.',
    9
  ),
  (
    'mustard',
    'Mustard',
    'Contains mustard or products derived from mustard.',
    10
  ),
  (
    'sesame',
    'Sesame',
    'Contains sesame seeds or products derived from sesame.',
    11
  ),
  (
    'sulphites',
    'Sulphites',
    'Contains sulphur dioxide or sulphites above the applicable threshold.',
    12
  ),
  (
    'lupin',
    'Lupin',
    'Contains lupin or products derived from lupin.',
    13
  ),
  (
    'molluscs',
    'Molluscs',
    'Contains molluscs or products derived from molluscs.',
    14
  );


-- ============================================================
-- 8. RLS
-- ============================================================

ALTER TABLE public.dietary_attributes
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.allergens
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.menu_item_dietary_attributes
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.menu_item_allergens
ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- 9. LEITURA DOS CATÁLOGOS
-- ============================================================

CREATE POLICY "dietary_attributes_select_authenticated"
ON public.dietary_attributes
FOR SELECT
TO authenticated
USING (
  is_active = true
);

CREATE POLICY "allergens_select_authenticated"
ON public.allergens
FOR SELECT
TO authenticated
USING (
  is_active = true
);


-- ============================================================
-- 10. PLATFORM ADMIN — GESTÃO DOS CATÁLOGOS
-- ============================================================

CREATE POLICY "dietary_attributes_manage_platform_admin"
ON public.dietary_attributes
FOR ALL
TO authenticated
USING (
  is_current_user_platform_admin()
)
WITH CHECK (
  is_current_user_platform_admin()
);

CREATE POLICY "allergens_manage_platform_admin"
ON public.allergens
FOR ALL
TO authenticated
USING (
  is_current_user_platform_admin()
)
WITH CHECK (
  is_current_user_platform_admin()
);


-- ============================================================
-- 11. LEITURA DAS CARACTERÍSTICAS DOS MENU ITEMS
-- ============================================================

CREATE POLICY "menu_item_dietary_attributes_select_authenticated"
ON public.menu_item_dietary_attributes
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.menu_items mi
    WHERE mi.id = menu_item_dietary_attributes.menu_item_id
  )
);

CREATE POLICY "menu_item_allergens_select_authenticated"
ON public.menu_item_allergens
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.menu_items mi
    WHERE mi.id = menu_item_allergens.menu_item_id
  )
);


-- ============================================================
-- 12. PLATFORM ADMIN — RELAÇÕES
-- ============================================================

CREATE POLICY "menu_item_dietary_attributes_manage_platform_admin"
ON public.menu_item_dietary_attributes
FOR ALL
TO authenticated
USING (
  is_current_user_platform_admin()
)
WITH CHECK (
  is_current_user_platform_admin()
);

CREATE POLICY "menu_item_allergens_manage_platform_admin"
ON public.menu_item_allergens
FOR ALL
TO authenticated
USING (
  is_current_user_platform_admin()
)
WITH CHECK (
  is_current_user_platform_admin()
);


-- ============================================================
-- 13. MANAGER — INSERIR CARACTERÍSTICAS
-- ============================================================

CREATE POLICY "menu_item_dietary_attributes_insert_manager"
ON public.menu_item_dietary_attributes
FOR INSERT
TO authenticated
WITH CHECK (
  is_current_user_restaurant_manager()
  AND EXISTS (
    SELECT 1
    FROM public.menu_items mi
    JOIN public.employees e
      ON e.restaurant_id = mi.restaurant_id
    JOIN public.roles r
      ON r.id = e.role_id
    WHERE mi.id = menu_item_dietary_attributes.menu_item_id
      AND e.user_id = auth.uid()
      AND e.status = 'active'
      AND r.name = 'manager'
  )
  AND EXISTS (
    SELECT 1
    FROM public.dietary_attributes da
    WHERE da.id = menu_item_dietary_attributes.dietary_attribute_id
      AND da.is_active = true
  )
);

CREATE POLICY "menu_item_allergens_insert_manager"
ON public.menu_item_allergens
FOR INSERT
TO authenticated
WITH CHECK (
  is_current_user_restaurant_manager()
  AND EXISTS (
    SELECT 1
    FROM public.menu_items mi
    JOIN public.employees e
      ON e.restaurant_id = mi.restaurant_id
    JOIN public.roles r
      ON r.id = e.role_id
    WHERE mi.id = menu_item_allergens.menu_item_id
      AND e.user_id = auth.uid()
      AND e.status = 'active'
      AND r.name = 'manager'
  )
  AND EXISTS (
    SELECT 1
    FROM public.allergens a
    WHERE a.id = menu_item_allergens.allergen_id
      AND a.is_active = true
  )
);


-- ============================================================
-- 14. MANAGER — REMOVER CARACTERÍSTICAS
-- ============================================================

CREATE POLICY "menu_item_dietary_attributes_delete_manager"
ON public.menu_item_dietary_attributes
FOR DELETE
TO authenticated
USING (
  is_current_user_restaurant_manager()
  AND EXISTS (
    SELECT 1
    FROM public.menu_items mi
    JOIN public.employees e
      ON e.restaurant_id = mi.restaurant_id
    JOIN public.roles r
      ON r.id = e.role_id
    WHERE mi.id = menu_item_dietary_attributes.menu_item_id
      AND e.user_id = auth.uid()
      AND e.status = 'active'
      AND r.name = 'manager'
  )
);

CREATE POLICY "menu_item_allergens_delete_manager"
ON public.menu_item_allergens
FOR DELETE
TO authenticated
USING (
  is_current_user_restaurant_manager()
  AND EXISTS (
    SELECT 1
    FROM public.menu_items mi
    JOIN public.employees e
      ON e.restaurant_id = mi.restaurant_id
    JOIN public.roles r
      ON r.id = e.role_id
    WHERE mi.id = menu_item_allergens.menu_item_id
      AND e.user_id = auth.uid()
      AND e.status = 'active'
      AND r.name = 'manager'
  )
);

