
-- ============================================================
-- RestaurantOS
-- Migration: platform admins e restaurant memberships
-- ============================================================


-- ============================================================
-- 1. Platform Admins
--
-- Platform Admin é um utilizador com acesso global à plataforma.
-- Não é um cargo dentro de um restaurante.
-- ============================================================

CREATE TABLE public.platform_admins (
  user_id uuid PRIMARY KEY
    REFERENCES auth.users(id)
    ON DELETE CASCADE,

  created_at timestamptz NOT NULL DEFAULT now()
);


-- ============================================================
-- 2. Restaurant Memberships
--
-- Uma membership representa o acesso de um utilizador
-- a um restaurante.
--
-- Não representa:
-- - cargo
-- - role
-- - permission
-- - employee
--
-- Um utilizador pode ter memberships em restaurantes diferentes,
-- mas cada Employee continua associado a apenas um restaurante.
-- ============================================================

CREATE TABLE public.restaurant_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id uuid NOT NULL
    REFERENCES auth.users(id)
    ON DELETE CASCADE,

  restaurant_id bigint NOT NULL
    REFERENCES public.restaurants(id)
    ON DELETE CASCADE,

  status text NOT NULL DEFAULT 'active',

  created_at timestamptz NOT NULL DEFAULT now(),

  created_by uuid
    REFERENCES auth.users(id)
    ON DELETE SET NULL,

  CONSTRAINT restaurant_memberships_status_valid
    CHECK (status IN ('active', 'inactive')),

  CONSTRAINT restaurant_memberships_user_restaurant_unique
    UNIQUE (user_id, restaurant_id)
);


-- ============================================================
-- 3. Índices
-- ============================================================

CREATE INDEX restaurant_memberships_user_id_idx
ON public.restaurant_memberships (user_id);

CREATE INDEX restaurant_memberships_restaurant_id_idx
ON public.restaurant_memberships (restaurant_id);

CREATE INDEX restaurant_memberships_created_by_idx
ON public.restaurant_memberships (created_by);

